/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// TaskSpecWithSizeApplyConfiguration represents a declarative configuration of the TaskSpecWithSize type for use
// with apply.
type TaskSpecWithSizeApplyConfiguration struct {
	Size     *int                        `json:"size,omitempty"`
	TaskSpec *TaskSpecApplyConfiguration `json:"taskSpec,omitempty"`
}

// TaskSpecWithSizeApplyConfiguration constructs a declarative configuration of the TaskSpecWithSize type for use with
// apply.
func TaskSpecWithSize() *TaskSpecWithSizeApplyConfiguration {
	return &TaskSpecWithSizeApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *TaskSpecWithSizeApplyConfiguration) WithSize(value int) *TaskSpecWithSizeApplyConfiguration {
	b.Size = &value
	return b
}

// WithTaskSpec sets the TaskSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaskSpec field is set to the value of the last call.
func (b *TaskSpecWithSizeApplyConfiguration) WithTaskSpec(value *TaskSpecApplyConfiguration) *TaskSpecWithSizeApplyConfiguration {
	b.TaskSpec = value
	return b
}
